name = "private-worker"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[vars] 
ENVIRONMENT = "dev"

r2_buckets = [
  { binding = 'JS_VARIABLE', bucket_name = 'private-r2-dev' }
]

[env.production]
vars = { ENVIRONMENT = "production" }

routes = [
	{ pattern = "api.example.com", custom_domain = true }
]

r2_buckets = [
  { binding = 'JS_VARIABLE', bucket_name = 'private-r2-prod' }
]
